const alex = {
  name: "ALEX полотенцесушитель",
  link: "/ALEX",
  items: [
    {
      id: 1,
      name: "Terma Alex 1140/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_1140_500_ral_9016_sx.png",
              "/assets/alex/alex_1140_500_ral_9016_sx_1.png",
              "/assets/alex/alex_1.png",
            ],
            cost: 192.29,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_1140_500_ral_6019_sx.png",
              "/assets/alex/alex_1140_500_ral_2011_sx.png",
              "/assets/alex/alex_3.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 240.36,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1140_500_cro_sx_1.png",
              "/assets/alex/alex_1580_600_chrome_yo_detal_1.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 559.23,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1140",
      weight: "500",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "600",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 2,
      name: "Terma Alex 760/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/polotentsesushitel_alex.jpg",
              "/assets/alex/full_328926.jpg",
              "/assets/alex/alex_760_500_ral_9016_sx.png",
              "/assets/alex/5901804234729_02c.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 145.37,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_760_500_ral_6005_sx.png",
              "/assets/alex/alex_760_500_ral_5009_sx.png",
              "/assets/alex/alex_760_500_ral_4005_sx.png",
              "/assets/alex/alex_760_500_ral_3000_sx.png",
              "/assets/alex/alex_760_500_ral_1011_sx.png",
              "/assets/alex/alex9.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 181.71,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo_detal_2.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 384.37,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "760",
      weight: "500",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 3,
      name: "Terma Alex 540/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/full_328926.jpg",
              "/assets/alex/alex_760_500_ral_9016_sx.png",
              "/assets/alex/polotentsesushitel_alex.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 122.29,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_540_500_ral_9005_sx.png",
              "/assets/alex/alex_540_500_ral_6019_sx.png",
              "/assets/alex/alex_540_500_ral_6018_sx.png",
              "/assets/alex/alex_540_500_ral_5007_sx.png",
              "/assets/alex/alex_540_500_ral_4006_sx.png",
              "/assets/alex/alex_540_500_ral_1032_sx.png",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 152.87,
          },
        },
        {
          Хром: {
            imgs: ["/assets/alex/alex-razmery.jpg"],
            cost: 296.76,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "540",
      weight: "500",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 4,
      name: "Terma Alex 540/400 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/full_328926.jpg",
              "/assets/alex/alex_540_400_ral_9016_sx.png",
              "/assets/alex/polotentsesushitel_alex.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 117.29,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_540_400_ral_9005_sx.png",
              "/assets/alex/alex_540_400_ral_4005_sx.png",
              "/assets/alex/alex_540_400_ral_3004_sx.png",
              "/assets/alex/alex_540_400_ral_1028_sx.png",
              "/assets/alex/terma-alex-2-600x600-700x700.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 146.62,
          },
        },
        {
          Хром: {
            imgs: ["/assets/alex/alex-razmery.jpg"],
            cost: 272.76,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "540",
      weight: "400",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "200",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 5,
      name: "Terma Alex 540/300 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_540_300_ral_9016_sx.png",
              "/assets/alex/terma-dziovintuvas-alex.jpg",
              "/assets/alex/al_2.png",
            ],
            cost: 112.68,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_540_300_ral_9005_sx.png",
              "/assets/alex/alex_540_300_ral_6027_sx.png",
              "/assets/alex/alex_540_300_ral_3018_sx.png",
              "/assets/alex/alex_540_300_ral_1018_sx.png",
              "/assets/alex/terma-alex-2-600x600-700x700.jpg",
              "/assets/alex/al_2.png",
            ],
            cost: 140.85,
          },
        },
        {
          Хром: {
            imgs: ["/assets/alex/al_2.png"],
            cost: 248.38,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "540",
      weight: "300",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "200",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 6,
      name: "Terma Alex 1580/800 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_1580_800_ral_9016_sx.png",
              "/assets/alex/alexrazm.png",
            ],
            cost: 301.89,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex-1000x600.jpg",
              "/assets/alex/alex_one_1580x500.jpg",
              "/assets/alex/alex_1580_800_ral_7034_sx.png",
              "/assets/alex/alex_1580_800_ral_3017_sx.png",
              "/assets/alex/alex_1580_800_ral_2010_sx.png",
              "/assets/alex/alex_1580_800_ral_1017_sx.png",
              "/assets/alex/alex_1580_800_ral_1012_sx.png",
              "/assets/alex/alex_1580_800_ral_5009_sx.png",
              "/assets/alex/alexrazm.png",
            ],
            cost: 377.36,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1580",
      weight: "800",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "1200",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 7,
      name: "Terma Alex 1580/700 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_1580_700_ral_9016_sx_1.png",
              "/assets/alex/alex_1580_700_ral_9016_sx.png",
              "/assets/alex/5901804234729_02c.jpg",
              "/assets/alex/alexrazm.png",
            ],
            cost: 279.2,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_3.jpg",
              "/assets/alex/alex-1000x600.jpg",
              "/assets/alex/alex_one_1580x500.jpg",
              "/assets/alex/alex_1580_700_ral_6006_sx.png",
              "/assets/alex/alex_1580_700_ral_3028_sx.png",
              "/assets/alex/alex_1580_700_ral_3014_sx.png",
              "/assets/alex/alex_1580_700_ral_4006_sx.png",
              "/assets/alex/alexrazm.png",
            ],
            cost: 349.0,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo.jpg",
              "/assets/alex/alex_1580_600_chrome_yo_detal_2.jpg",
              "/assets/alex/alexrazm.png",
            ],
            cost: 878.84,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1580",
      weight: "700",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "1000",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 16,
      name: "Terma Alex 1580/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_1580_600_ral_9016_sx_1.png",
              "/assets/alex/alexrazm.png",
            ],
            cost: 258.43,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex-1000x600.jpg",
              "/assets/alex/alex_one_1580x500.jpg",
              "/assets/alex/alex_1580_600_ral_5004_sx.png",
              "/assets/alex/alex_1580_600_ral_5024_sx.png",
              "/assets/alex/alex_1580_600_ral_3028_sx.png",
              "/assets/alex/alex_1580_600_ral_3013_sx.png",
              "/assets/alex/alexrazm.png",
            ],
            cost: 323.04,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo.jpg",
              "/assets/alex/alex_1580_600_chrome_yo_detal_1.jpg",
              "/assets/alex/alex_1580_600_cro_sx_1.png",
              "/assets/alex/alexrazm.png",
            ],
            cost: 804.18,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1580",
      weight: "600",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "1000",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 8,
      name: "Terma Alex 1580/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_1580_500_ral_9016_sx.png",
              "/assets/alex/5901804234729_02c.jpg",
              "/assets/alex/alexrazm.png",
            ],
            cost: 237.67,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex_1580_600_ral_5024_sx.png",
              "/assets/alex/alex_1580_600_ral_3028_sx.png",
              "/assets/alex/alex_1580_600_ral_3013_sx.png",
              "/assets/alex/alex9.jpg",
              "/assets/alex/terma-alex-2-600x600-700x700.jpg",
              "/assets/alex/alexrazm.png",
            ],
            cost: 297.08,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo.jpg",
              "/assets/alex/alex_1580_600_chrome_yo_detal_1.jpg",
              "/assets/alex/alexrazm.png",
            ],
            cost: 734.08,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1580",
      weight: "500",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "800",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 9,
      name: "Terma Alex 1140/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_1140_600_ral_9016_sx.png",
              "/assets/alex/5901804234729_02c.jpg",
              "/assets/alex/alexrazm.png",
            ],
            cost: 211.13,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_1140_600_ral_3009_sx.png",
              "/assets/alex/alex_1140_600_ral_3001_sx.png",
              "/assets/alex/alex_1140_600_ral_9005_sx.png",
              "/assets/alex/alex_3.jpg",
              "/assets/alex/alex_tehkarta_polotentsesushitel_terma_1.jpg",
            ],
            cost: 263.91,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1140_600_cro_sx_1.png",
              "/assets/alex/alex_1580_600_chrome_yo_detal_2.jpg",
              "/assets/alex/alex_tehkarta_polotentsesushitel_terma_1.jpg",
            ],
            cost: 610.66,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1140",
      weight: "600",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "800",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 10,
      name: "Terma Alex 1140/400 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_1140_400_ral_9016_sx.png",
              "/assets/alex/5901804234729_02c.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 177.29,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_1140_400_ral_6017_sx.png",
              "/assets/alex/alex_1140_400_ral_4011_sx.png",
              "/assets/alex/alex_1140_400_ral_4002_sx.png",
              "/assets/alex/alex_3.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 221.61,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo_detal_2.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 505.51,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1140",
      weight: "400",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 11,
      name: "Terma Alex 1140/300 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_1140_300_ral_9016_sx.png",
              "/assets/alex/alex_1.png",
            ],
            cost: 162.29,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_1140_300_ral_5007_sx.png",
              "/assets/alex/alex_1140_300_ral_4007_sx.png",
              "/assets/alex/alex_1140_300_ral_1003_sx.png",
              "/assets/alex/alex_1140_300_ral_9005_sx.png",
              "/assets/alex/alex_1140_300_ral_7036_sx.png",
              "/assets/alex/alex_3.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 202.86,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo_detal_2.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 449.52,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1140",
      weight: "300",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 12,
      name: "Terma Alex 760/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/00000002963_1.jpg",
              "/assets/alex/5901804234729_02c.jpg",
              "/assets/alex/alex_760_600_ral_9016_sx.png",
              "/assets/alex/alex_1.png",
            ],
            cost: 158.44,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_760_600_ral_6029_sx.png",
              "/assets/alex/alex_760_600_ral_6009_sx.png",
              "/assets/alex/alex_760_600_ral_5000_sx.png",
              "/assets/alex/alex_760_600_ral_4007_sx.png",
              "/assets/alex/alex_1.png",
            ],
            cost: 198.06,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo_detal_2.jpg",
              "/assets/alex/alex_1.png",
            ],
            cost: 419.42,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1140",
      weight: "300",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 13,
      name: "Terma Alex 760/400 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/00000002963_1_1.jpg",
              "/assets/alex/alex_760_400_ral_9016_sx.png",
              "/assets/alex/5901804234729_02c.jpg",
              "/assets/alex/polotentsesushitel_alex.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 135.75,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_760_400_ral_9005_sx.png",
              "/assets/alex/alex_760_400_ral_6018_sx.png",
              "/assets/alex/alex_760_400_ral_6001_sx.png",
              "/assets/alex/alex_760_400_ral_4005_sx.png",
              "/assets/alex/alex_760_400_ral_3000_sx.png",
              "/assets/alex/terma-alex-2-600x600-700x700.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 169.69,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo_detal.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 351.23,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "760",
      weight: "400",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 14,
      name: "Terma Alex 760/300 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/00000002963_1.jpg",
              "/assets/alex/5901804234729_02c.jpg",
              "/assets/alex/polotentsesushitel_alex.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 128.45,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex.jpg",
              "/assets/alex/alex_760_300_ral_9005_sx.png",
              "/assets/alex/alex_760_300_ral_6033_sx.png",
              "/assets/alex/alex_760_300_ral_4003_sx.png",
              "/assets/alex/alex_760_300_ral_3000_sx.png",
              "/assets/alex/alex_760_300_ral_2012_sx.png",
              "/assets/alex/terma-alex-2-600x600-700x700.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 160.56,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/alex/alex_1580_600_chrome_yo_detal_1.jpg",
              "/assets/alex/alex-razmery.jpg",
            ],
            cost: 318.85,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "760",
      weight: "300",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 15,
      name: "Terma Alex 540/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/alex/alex_540_600_ral_9016_sx.png",
              "/assets/alex/full_328926.jpg",
              "/assets/alex/polotentsesushitel_alex.jpg",
              "/assets/alex/alex_540_600.jpg",
            ],
            cost: 128.45,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/alex/alex_540_600_ral_6024_sx.png",
              "/assets/alex/alex_540_600_ral_6013_sx.png",
              "/assets/alex/alex_540_600_ral_5018_sx.png",
              "/assets/alex/alex_540_600_ral_4006_sx.png",
              "/assets/alex/alex_540_600_ral_3003_sx.png",
              "/assets/alex/alex_540_600_ral_1033_sx.png",
              "/assets/alex/terma-alex-2-600x600-700x700.jpg",
              "/assets/alex/alex_540_600.jpg",
            ],
            cost: 160.56,
          },
        },
        {
          Хром: {
            imgs: ["/assets/alex/alex_540_600.jpg"],
            cost: 320.37,
          },
        },
      ],
      desc: `Alex - простой и элегантный прибор. Идеально подойдёт, как в классические, так и современные интерьеры ванных комнат и кухни. Будет всегда радовать своим цветом, и формой. Тепловая мощность: 180-1253 Вт.Возможность использования электронагревателя`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "760",
      weight: "300",
      glub: "120",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
  ],
};
