const bone = {
  name: "BONE полотенцесушитель",
  link: "/BONE",
  items: [
    {
      id: 27,
      name: "Terma Bone DW 1910/500 разделительная стенка",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/terma_bonedw3.jpg",
              "/assets/bone/bone_dw_1910_500_ral_9016_o1.png",
              "/assets/bone/22321_0_1024.jpg",
              "/assets/bone/1af58e680620cb33a6289245ac3e9c42.png",
            ],
            cost: 412.69,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/terma_bonedw1.jpg",
              "/assets/bone/bone_dw_1910_500_ral_3028_o1.png",
              "/assets/bone/bone_dw_1910_500_ral_3022_o1.png",
              "/assets/bone/bone_dw_1910_500_ral_4011_o1.png",
              "/assets/bone/22321_0_1024.jpg",
              "/assets/bone/bone_dw_1610_500_noble_brown_det_2.jpg",
              "/assets/bone/bone_dw_1610_500_noble_brown_det.jpg",
              "/assets/bone/1af58e680620cb33a6289245ac3e9c42.png",
            ],
            cost: 515.0,
          },
        },
      ],
      desc: `Полотенцесушитель Bone DW в варианте разделительной перегородки решает задачу освещения помещения и его разделения на зоны. Лёгкость, симметричность корпуса обогревателя соответствует современным тенденциям. Bone в версии разделительной стенки помогает в остроумный, и невынужденный способ реализовать самые необычные решения. Доступен в версиях: водной, водно-электрической, электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1910",
      weight: "500",
      glub: "560",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "600",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 28,
      name: "Terma Bone 1610/500 разделительная стенка",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/bone_dw_1610_500_ral_9016_o1.png",
              "/assets/bone/terma_bonedw3.jpg",
              "/assets/bone/22321_0_1024.jpg",
              "/assets/bone/1af58e680620cb33a6289245ac3e9c42.png",
            ],
            cost: 374.54,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/terma_bonedw1.jpg",
              "/assets/bone/bone_dw_1610_500_ral_6000_o1.png",
              "/assets/bone/bone_dw_1610_500_ral_3028_o1.png",
              "/assets/bone/bone_dw_1610_500_ral_1004_o1.png",
              "/assets/bone/22321_0_1024.jpg",
              "/assets/bone/ge-catalog-terma-bone-terma_bone_dw_d4_1785a-1000x1000.jpg",
              "/assets/bone/bone_dw_1610_500_noble_brown_det_2.jpg",
              "/assets/bone/bone_dw_1610_500_noble_brown_det.jpg",
              "/assets/bone/bone_dw_1610_500_noble_brown.jpg",
              "/assets/bone/1af58e680620cb33a6289245ac3e9c42.png",
            ],
            cost: 468.18,
          },
        },
      ],
      desc: `Полотенцесушитель Bone DW в варианте разделительной перегородки решает задачу освещения помещения и его разделения на зоны. Лёгкость, симметричность корпуса обогревателя соответствует современным тенденциям. Bone в версии разделительной стенки помогает в остроумный, и невынужденный способ реализовать самые необычные решения. Доступен в версиях: водной, водно-электрической, электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1610",
      weight: "500",
      glub: "560",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "600",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 29,
      name: "Terma Bone 1510/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/bone_1510_600_ral_9016_sx.png",
              "/assets/bone/bone_1510_600_ral_9016_sx_1.png",
              "/assets/bone/229331.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 269.03,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/bone_1510_600_ral_6002_sx.png",
              "/assets/bone/bone_1510_600_ral_3028_sx.png",
              "/assets/bone/bone_1510_600_ral_3028_sx_1.png",
              "/assets/bone/bone_1510_600_ral_1016_sx.png",
              "/assets/bone/bone_1510_600_metallic_stone_interior_panorama.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 336.28,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/bone/bone_1510_610_cro_sx.png",
              "/assets/bone/bone_1510_610_cro_sx_1.png",
              "/assets/bone/59fb0a54a694c.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 813.02,
          },
        },
      ],
      desc: `Симметричный корпус полотенцесушителя отлично вписывается в современные тенденции рынка. Bone является отличным решением для современных дизайнов. Он сочетает в себе минимализм, простору и функциональность, а также эффективно выполняет функцию полотенцесушителя. Доступен в версии водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1510",
      weight: "600",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 30,
      name: "Terma Bone 1510/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/bone_1510_500_ral_9016_sx.png",
              "/assets/bone/bone_1510_500_ral_9016_sx_1.png",
              "/assets/bone/229331.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 256.2,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/bone_1510_500_ral_5024_sx.png",
              "/assets/bone/bone_1510_500_ral_3028_sx.png",
              "/assets/bone/bone_1510_500_ral_2012_sx.png",
              "/assets/bone/bone_1510_500_ral_7048_sx.png",
              "/assets/bone/bone_1510_600_metallic_stone_interior_panorama.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 320.25,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/bone/bone_1510_500_cro_sx.png",
              "/assets/bone/bone_1510_500_cro_sx_1.png",
              "/assets/bone/59fb0a54a694c.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 720.51,
          },
        },
      ],
      desc: `Симметричный корпус полотенцесушителя отлично вписывается в современные тенденции рынка. Bone является отличным решением для современных дизайнов. Он сочетает в себе минимализм, простору и функциональность, а также эффективно выполняет функцию полотенцесушителя. Доступен в версии водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1510",
      weight: "500",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 31,
      name: "Terma Bone 1260/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/bone_1260_600_ral_9016_sx.png",
              "/assets/bone/bone_1260_600_ral_9016_sx_1.png",
              "/assets/bone/229331.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 227.9,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/bone_1260_600_ral_3028_sx.png",
              "/assets/bone/bone_1260_600_ral_1024_sx.png",
              "/assets/bone/bone_1260_500_ral_8022_sx.png",
              "/assets/bone/bone_1260_600_ral_5002_sx.png",
              "/assets/bone/bone_760_500_metallic_grey_lifestyle_300dpi-min_1024x1024.jpg",
              "/assets/bone/max-20170925140004376.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 284.87,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/bone/bone_1260_600_cro_sx.png",
              "/assets/bone/bone_1260_600_cro_sx_1.png",
              "/assets/bone/59fb0a54a694c.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 590.99,
          },
        },
      ],
      desc: `Симметричный корпус полотенцесушителя отлично вписывается в современные тенденции рынка. Bone является отличным решением для современных дизайнов. Он сочетает в себе минимализм, простору и функциональность, а также эффективно выполняет функцию полотенцесушителя. Доступен в версии водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1260",
      weight: "600",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 32,
      name: "Terma Bone 1260/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/bone_1260_500_ral_9016_sx.png",
              "/assets/bone/bone_1260_500_ral_9016_sx_1.png",
              "/assets/bone/229331.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 216.58,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/bone_1260_500_ral_8022_sx.png",
              "/assets/bone/bone_1260_500_ral_3028_sx_1.png",
              "/assets/bone/bone_1260_500_ral_3028_sx.png",
              "/assets/bone/bone_1260_500_ral_1012_sx.png",
              "/assets/bone/bone_1260_500_cro_sx.png",
              "/assets/bone/229331.jpg",
              "/assets/bone/bone_1510_600_metallic_stone_interior_panorama.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 270.73,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/bone/bone_1260_500_cro_sx.png",
              "/assets/bone/bone_1260_500_cro_sx_1.png",
              "/assets/bone/59fb0a54a694c.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 516.98,
          },
        },
      ],
      desc: `Симметричный корпус полотенцесушителя отлично вписывается в современные тенденции рынка. Bone является отличным решением для современных дизайнов. Он сочетает в себе минимализм, простору и функциональность, а также эффективно выполняет функцию полотенцесушителя. Доступен в версии водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1260",
      weight: "500",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 33,
      name: "Terma Bone 760/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/bone_760_600_ral_9016_sx.png",
              "/assets/bone/bone_760_600_ral_9016_sx_1.png",
              "/assets/bone/229331.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 187.53,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/bone_760_600_ral_3028_sx.png",
              "/assets/bone/bone_760_600_ral_3015_sx.png",
              "/assets/bone/bone_760_600_cro_sx.png",
              "/assets/bone/bone_760_600_ral_3007_sx.png",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 234.41,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/bone/bone_760_600_cro_sx.png",
              "/assets/bone/bone_760_600_cro_sx_1.png",
              "/assets/bone/59fb0a54a694c.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 443.33,
          },
        },
      ],
      desc: `Симметричный корпус полотенцесушителя отлично вписывается в современные тенденции рынка. Bone является отличным решением для современных дизайнов. Он сочетает в себе минимализм, простору и функциональность, а также эффективно выполняет функцию полотенцесушителя. Доступен в версии водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "760",
      weight: "600",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 34,
      name: "Terma Bone 760/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/bone_760_500_ral_9016_sx_1.png",
              "/assets/bone/229331.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 180.73,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/bone_760_500_ral_3015_sx.png",
              "/assets/bone/bone_760_500_ral_6034_sx.png",
              "/assets/bone/bone_760_500_ral_5010_sx.png",
              "/assets/bone/bone_760_500_ral_3028_sx.png",
              "/assets/bone/bone_760_500_ral_1012_sx.png",
              "/assets/bone/bone_760_500_metallic_grey_lifestyle_300dpi-min_1024x1024.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 225.92,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/bone/bone_760_500_cro_sx.png",
              "/assets/bone/bone_760_500_cro_sx_1.png",
              "/assets/bone/59fb0a54a694c.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 406.33,
          },
        },
      ],
      desc: `Симметричный корпус полотенцесушителя отлично вписывается в современные тенденции рынка. Bone является отличным решением для современных дизайнов. Он сочетает в себе минимализм, простору и функциональность, а также эффективно выполняет функцию полотенцесушителя. Доступен в версии водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "760",
      weight: "500",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
    {
      id: 35,
      name: "Terma Bone 510/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/bone/229331.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 131.78,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/bone/bone_760_500_metallic_grey_lifestyle_300dpi-min_1024x1024.jpg",
              "/assets/bone/max-20170925140004376.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 164.73,
          },
        },
        {
          Хром: {
            imgs: [
              "/assets/bone/bone_760_500_cro_sx.png",
              "/assets/bone/bone_760_500_cro_sx_1.png",
              "/assets/bone/59fb0a54a694c.jpg",
              "/assets/bone/max-20170925140004376.jpg",
              "/assets/bone/2019-03-12_13-55-29-1.png",
            ],
            cost: 392.84,
          },
        },
      ],
      desc: `Симметричный корпус полотенцесушителя отлично вписывается в современные тенденции рынка. Bone является отличным решением для современных дизайнов. Он сочетает в себе минимализм, простору и функциональность, а также эффективно выполняет функцию полотенцесушителя. Доступен в версии водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "510",
      weight: "500",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [
        {
          name: "Terma тэн MEG",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "20",
          img: "/assets/meg/meg_916.jpg",
        },
        {
          name: "Terma тэн MOA",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "21",
          img: "/assets/moa/moa_916.jpg",
        },
        {
          name: "Terma тэн DRY",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "22",
          img: "/assets/dry/dry_916.jpg",
        },
        {
          name: "Terma тэн REG3",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "23",
          img: "/assets/reg3/reg3_white_terma.jpg",
        },
        {
          name: "Terma тэн REG2",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/reg2/terma_reg_2_white_1.png",
        },
        {
          name: "Terma тэн MOA(Blue)",
          producer: "Terma",
          cost: "6 428",
          link: "/terma/ten/2",
          id: "24",
          img: "/assets/moa/moa_blue_916_m.jpg",
        },
      ],
    },
  ],
};
