const incorner = {
  name: "INCORNER полотенцесушитель",
  link: "/INCORNER",
  items: [
    {
      id: 99,
      name: "Terma Incorner 1545/350 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/incorner/terma_incorner_electro_3.jpg",
              "/assets/incorner/incorner_1545_350_ral_9016_sx.png",
              "/assets/incorner/incorner_1545x350.png",
            ],
            cost: 436.11,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/incorner/terma_incorner_front_pergamon.jpg",
              "/assets/incorner/terma_incorner_detal_pergamon.jpg",
              "/assets/incorner/ranksluosciu-dziovintuvas-terma-incorner.jpg",
              "/assets/incorner/incorner_1545_350_ral_5017_sx.png",
              "/assets/incorner/incorner_1545_350_ral_3018_sx.png",
              "/assets/incorner/incorner_1275_350_ral3005_det2.jpg",
              "/assets/incorner/incorner_1275_350_ral3005_det.jpg",
              "/assets/incorner/incorner_1005_350_modern_grey_d.jpg",
              "/assets/incorner/incorner_1545x350.png",
            ],
            cost: 457.92,
          },
        },
      ],
      desc: `Необычный полотенцесушитель идеально подходит для размещения в небольших комнатах, оформление которых выполнено в классическом стиле. Оригинальная эстетика, интересное и функциональное расположение труб, делает Incorner идеальным для максимального использования пространства дома. Доступные цвета позволяют удачно расположить полотенцесушитель в интерьере или прекрасно выделить его на стене, что делает его замечательным украшением в помещении.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1545",
      weight: "350",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 100,
      name: "Terma Incorner 1275/350 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/incorner/incorner_1275_350_ral_9016_sx.png",
              "/assets/incorner/ranksluosciu-dziovintuvas-terma-incorner.jpg",
              "/assets/incorner/terma_incorner_detal_pergamon.jpg",
              "/assets/incorner/incorner_1275x350.png",
            ],
            cost: 383.21,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/incorner/ac7447eaaf31bd0de21c2eec36349bf9.jpg",
              "/assets/incorner/incorner_1275_350_ral3005_det.jpg",
              "/assets/incorner/incorner_1275_350_ral3005.jpg",
              "/assets/incorner/incorner_1275_350_ral3005_det2.jpg",
              "/assets/incorner/incorner01.jpg",
              "/assets/incorner/incorner_1275_350_ral_1006_sx.png",
              "/assets/incorner/incorner_1275_350_ral_6024_sx.png",
              "/assets/incorner/incorner_1275x350.png",
            ],
            cost: 402.29,
          },
        },
      ],
      desc: `Необычный полотенцесушитель идеально подходит для размещения в небольших комнатах, оформление которых выполнено в классическом стиле. Оригинальная эстетика, интересное и функциональное расположение труб, делает Incorner идеальным для максимального использования пространства дома. Доступные цвета позволяют удачно расположить полотенцесушитель в интерьере или прекрасно выделить его на стене, что делает его замечательным украшением в помещении.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1275",
      weight: "350",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 101,
      name: "Terma Incorner 1005/350 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/incorner/incorner_1005_350_sea_salt.jpg",
              "/assets/incorner/terma_incorner_electro_3.jpg",
              "/assets/incorner/terma_incorner_detal_pergamon.jpg",
              "/assets/incorner/incorner_1005_350_ral_9016_sx.png",
              "/assets/incorner/incorner_735x350.png",
            ],
            cost: 348.53,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/incorner/incorner01.jpg",
              "/assets/incorner/incorner_1005_350_chrome_effect.jpg",
              "/assets/incorner/incorner_1275_350_ral3005_det.jpg",
              "/assets/incorner/incorner_1275_350_ral3005_det2.jpg",
              "/assets/incorner/incorner_1005_350_chrome_effect_d.jpg",
              "/assets/incorner/incorner_735x350.png",
            ],
            cost: 365.87,
          },
        },
      ],
      desc: `Необычный полотенцесушитель идеально подходит для размещения в небольших комнатах, оформление которых выполнено в классическом стиле. Оригинальная эстетика, интересное и функциональное расположение труб, делает Incorner идеальным для максимального использования пространства дома. Доступные цвета позволяют удачно расположить полотенцесушитель в интерьере или прекрасно выделить его на стене, что делает его замечательным украшением в помещении.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1005",
      weight: "350",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 102,
      name: "Terma Incorner 735/350 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/incorner/incorner_1005_350_sea_salt.jpg",
              "/assets/incorner/incorner_735_350_ral_9016_sx.png",
              "/assets/incorner/incorner_735x350.png",
            ],
            cost: 319.06,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/incorner/terma_incorner_electro_3.jpg",
              "/assets/incorner/terma_incorner_detal_pergamon.jpg",
              "/assets/incorner/ranksluosciu-dziovintuvas-terma-incorner.jpg",
              "/assets/incorner/incorner_735_350_ral_3020_sx.png",
              "/assets/incorner/incorner_735_350_ral_1005_sx.png",
              "/assets/incorner/incorner_1275_350_ral3005_det2.jpg",
              "/assets/incorner/incorner_735x350.png",
            ],
            cost: 334.66,
          },
        },
      ],
      desc: `Необычный полотенцесушитель идеально подходит для размещения в небольших комнатах, оформление которых выполнено в классическом стиле. Оригинальная эстетика, интересное и функциональное расположение труб, делает Incorner идеальным для максимального использования пространства дома. Доступные цвета позволяют удачно расположить полотенцесушитель в интерьере или прекрасно выделить его на стене, что делает его замечательным украшением в помещении.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "735",
      weight: "350",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 103,
      name: "Terma Incorner 465/350 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/incorner/incorner_1005_350_sea_salt.jpg",
              "/assets/incorner/incorner_465_350_ral_9016_sx.png",
              "/assets/incorner/terma_incorner_detal_pergamon.jpg",
              "/assets/incorner/ac7447eaaf31bd0de21c2eec36349bf9.jpg",
              "/assets/incorner/incorner_465x350.png",
            ],
            cost: 287.84,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/incorner/incorner_1005_350_modern_grey_nowy.jpg",
              "/assets/incorner/incorner_465_350_ral_1021_sx.png",
              "/assets/incorner/incorner_465_350_ral_2012_sx.png",
              "/assets/incorner/incorner_1005_350_modern_grey_d.jpg",
              "/assets/incorner/incorner_1005_350_chrome_effect_d.jpg",
              "/assets/incorner/incorner_465x350.png",
            ],
            cost: 301.72,
          },
        },
      ],
      desc: `Необычный полотенцесушитель идеально подходит для размещения в небольших комнатах, оформление которых выполнено в классическом стиле. Оригинальная эстетика, интересное и функциональное расположение труб, делает Incorner идеальным для максимального использования пространства дома. Доступные цвета позволяют удачно расположить полотенцесушитель в интерьере или прекрасно выделить его на стене, что делает его замечательным украшением в помещении.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "465",
      weight: "350",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
  ],
};
