const lukka = {
  name: "LUKKA полотенцесушитель",
  link: "/LUKKA",
  items: [
    {
      id: 160,
      name: "Terma Lukka 1660/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1660_600_ral_9016_sx.png",
              "/assets/lukka/lukka_1660_600_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 494.07,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1660_600_ral_6013_sx.png",
              "/assets/lukka/lukka_1660_600_ral_6003_sx.png",
              "/assets/lukka/lukka_1660_600_ral_3001_sx.png",
              "/assets/lukka/lukka_1660_600_ral_2010_sx.png",
              "/assets/lukka/terma_lukka_2.jpg",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/terma_lima_modelnyj_ryad_tiporazmery_700.jpg",
            ],
            cost: 518.77,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1660",
      weight: "600",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 161,
      name: "Terma Lukka 1660/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1660_500_ral_9016_sx.png",
              "/assets/lukka/lukka_1660_500_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 460.78,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1660_500_ral_7021_sx.png",
              "/assets/lukka/lukka_1660_500_ral_5018_sx.png",
              "/assets/lukka/lukka_1660_500_ral_4010_sx.png",
              "/assets/lukka/lukka_1660_500_ral_1034_sx.png",
              "/assets/lukka/lukka_1660_500_ral_1016_sx.png",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/lukka_1180_500_winter_sky.jpg",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 483.82,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1660",
      weight: "500",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 162,
      name: "Terma Lukka 1660/400 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1660_400_ral_9016_sx.png",
              "/assets/lukka/lukka_1660_400_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 426.41,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1660_400_ral_8016_sx.png",
              "/assets/lukka/lukka_1660_400_ral_5018_sx.png",
              "/assets/lukka/lukka_1660_400_ral_3009_sx.png",
              "/assets/lukka/lukka_1660_400_ral_1017_sx.png",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/lukka_1180_500_winter_sky.jpg",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 447.73,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1660",
      weight: "400",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 163,
      name: "Terma Lukka 1420/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1420_600_ral_9016_sx.png",
              "/assets/lukka/lukka_1420_600_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 453.33,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1420_600_ral_5013_sx_1.png",
              "/assets/lukka/lukka_1420_600_ral_4010_sx.png",
              "/assets/lukka/lukka_1420_600_ral_4010_sx_1.png",
              "/assets/lukka/lukka_1420_600_ral_1035_sx.png",
              "/assets/lukka/lukka_1420_600_ral_1020_sx.png",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/lukka_1180_500_winter_sky.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 475.99,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1420",
      weight: "600",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 164,
      name: "Terma Lukka 1420/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1420_500_ral_9016_sx.png",
              "/assets/lukka/lukka_1420_500_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 424.82,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1420_500_ral_6004_sx.png",
              "/assets/lukka/lukka_1420_500_ral_5024_sx.png",
              "/assets/lukka/lukka_1420_500_ral_4001_sx.png",
              "/assets/lukka/lukka_1420_500_ral_3001_sx.png",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/lukka_1180_500_winter_sky.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 446.06,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1420",
      weight: "500",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 165,
      name: "Terma Lukka 1420/400 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1420_400_ral_9016_sx.png",
              "/assets/lukka/lukka_1420_400_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 395.25,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1420_400_ral_4006_sx.png",
              "/assets/lukka/lukka_1420_400_ral_3001_sx.png",
              "/assets/lukka/lukka_1420_400_ral_5007_sx.png",
              "/assets/lukka/lukka_1420_400_ral_6020_sx.png",
              "/assets/lukka/lukka_1420_400_ral_1035_sx.png",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/lukka_1180_500_winter_sky.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 415.01,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1420",
      weight: "400",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 166,
      name: "Terma Lukka 1180/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1180_600_ral_9016_sx.png",
              "/assets/lukka/lukka_1180_600_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 412.65,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1180_600_ral_6028_sx.png",
              "/assets/lukka/lukka_1180_600_ral_5000_sx.png",
              "/assets/lukka/lukka_1180_600_ral_4007_sx.png",
              "/assets/lukka/lukka_1180_600_ral_1032_sx.png",
              "/assets/lukka/lukka_1180_600_ral_1024_sx.png",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 433.29,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1180",
      weight: "600",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 167,
      name: "Terma Lukka 1180/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1180_500_ral_9016_sx.png",
              "/assets/lukka/lukka_1180_500_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 388.67,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1180_500_ral_4007_sx.png",
              "/assets/lukka/lukka_1180_500_ral_4005_sx.png",
              "/assets/lukka/lukka_1180_500_ral_2001_sx.png",
              "/assets/lukka/lukka_1180_500_ral_1028_sx.png",
              "/assets/lukka/lukka_1180_500_ral_1019_sx.png",
              "/assets/lukka/lukka_1180_500_winter_sky.jpg",
              "/assets/lukka/terma_lukka_2.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 408.1,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1180",
      weight: "500",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 168,
      name: "Terma Lukka 1180/400 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_1180_400_ral_9016_sx.png",
              "/assets/lukka/lukka_1180_400_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 364.75,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_1180_400_ral_3004_sx.png",
              "/assets/lukka/lukka_1180_400_ral_1006_sx.png",
              "/assets/lukka/lukka_1180_400_ral_1001_sx.png",
              "/assets/lukka/terma_lukka_2.jpg",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 382.99,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1180",
      weight: "400",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 169,
      name: "Terma Lukka 940/600 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_940_600_ral_9016_sx_1.png",
              "/assets/lukka/lukka_940_600_ral_9016_sx.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 369.69,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_940_600_ral_5012_sx.png",
              "/assets/lukka/lukka_940_600_ral_4011_sx.png",
              "/assets/lukka/lukka_940_600_ral_3016_sx.png",
              "/assets/lukka/lukka_940_600_ral_2012_sx.png",
              "/assets/lukka/terma_lukka_2.jpg",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 388.18,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "940",
      weight: "600",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 170,
      name: "Terma Lukka 940/500 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_940_500_ral_9016_sx.png",
              "/assets/lukka/lukka_940_500_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 351.37,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_940_500_ral_5015_sx.png",
              "/assets/lukka/lukka_940_500_ral_5009_sx.png",
              "/assets/lukka/lukka_940_500_ral_3004_sx.png",
              "/assets/lukka/lukka_940_500_ral_3000_sx.png",
              "/assets/lukka/terma_lukka_2.jpg",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 368.94,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "940",
      weight: "500",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 171,
      name: "Terma Lukka 940/400 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/lukka/lukka_940_400_ral_9016_sx.png",
              "/assets/lukka/lukka_940_400_ral_9016_sx_1.png",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 332.24,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/lukka/lukka_940_400_ral_6022_sx.png",
              "/assets/lukka/lukka_940_400_ral_1018_sx.png",
              "/assets/lukka/lukka_940_400_ral_1014_sx.png",
              "/assets/lukka/lukka_940_400_ral_4009_sx.png",
              "/assets/lukka/lukka_940_400_ral_2008_sx.png",
              "/assets/lukka/terma_lukka_2.jpg",
              "/assets/lukka/lukka_1180_500_ral5023_poziom.jpg",
              "/assets/lukka/23591345x0.jpg",
              "/assets/lukka/l2.jpg",
            ],
            cost: 348.85,
          },
        },
      ],
      desc: `Трубчатый полотенцесушитель спроектированный на основе рамы, имеющей круглое окончание коллектора и полуовальную трубку закрывающую корпус. Плоские трубки внутри рамы придают всей конструкции оригинальный внешний вид. Lukka - это современный полотенцесушитель имеющий мягкие линии, придающие интерьеру уют.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "940",
      weight: "400",
      glub: "72",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "400",
      guaranty: "8",
      recommendations: [],
    },
  ],
};
