const outcorner = {
  name: "OUTCORNER полотенцесушитель",
  link: "/OUTCORNER",
  items: [
    {
      id: 104,
      name: "Terma Outcorner 1545/300 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/outcorner/outcorner_1545_300_ral_9016_sx.png",
              "/assets/outcorner/outcorner_1545x300.png",
              "/assets/outcorner/1077815_54585454.jpg",
              "/assets/outcorner/terma_outcorner_electro_4.jpg",
            ],
            cost: 417.89,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/outcorner/terma_outcorner2.jpg",
              "/assets/outcorner/outcorner_1545_300_ral_9016_sx.png",
              "/assets/outcorner/outcorner_1545_300_ral_5002_sx.png",
              "/assets/outcorner/outcorner_1545_300_ral_1011_sx.png",
              "/assets/outcorner/ranksluosciu-dziovintuvas-outcorner_2.jpg",
              "/assets/outcorner/terma_outcorner1.png",
              "/assets/outcorner/outcorner_1545x300.png",
            ],
            cost: 438.7,
          },
        },
      ],
      desc: `Там, где ведется поиски свободного пространства и использовать каждый его сантиметр, там используются нестандартные решения. Декоративный полотенцесушитель Outcorner идеально подходит для обустройства небольших, искусно оформленных помещений. Он характеризуется оригинальной эстетикой и интересным и функциональным расположением профилей. Outcorner идеально подходит для помещений, в которых есть колонны и выступающие плоскости где Outcorner может быть интересным и продуманным решением планировки. Дополнительные крючки ZIP дополняют полотенцесушитель, делая его более функциональным. Полотенцесушитель доступен в версии с водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1545",
      weight: "300",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 105,
      name: "Terma Outcorner 1275/300 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/outcorner/23622750x0.jpg",
              "/assets/outcorner/terma_incorner_detal_pergamon.jpg",
              "/assets/outcorner/outcorner_1275x300.png",
            ],
            cost: 383.21,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/outcorner/outcorner_1275_300_ral_5005_sx.png",
              "/assets/outcorner/outcorner_1275_300_ral_2009_sx.png",
              "/assets/outcorner/terma_outcorner.jpg",
              "/assets/outcorner/terma_outcorner2.jpg",
              "/assets/outcorner/terma_outcorner1.png",
              "/assets/outcorner/ranksluosciu-dziovintuvas-outcorner_2.jpg",
              "/assets/outcorner/terma_outcorner_electro_3.jpg",
              "/assets/outcorner/outcorner_1275x300.png",
            ],
            cost: 402.29,
          },
        },
      ],
      desc: `Там, где ведется поиски свободного пространства и использовать каждый его сантиметр, там используются нестандартные решения. Декоративный полотенцесушитель Outcorner идеально подходит для обустройства небольших, искусно оформленных помещений. Он характеризуется оригинальной эстетикой и интересным и функциональным расположением профилей. Outcorner идеально подходит для помещений, в которых есть колонны и выступающие плоскости где Outcorner может быть интересным и продуманным решением планировки. Дополнительные крючки ZIP дополняют полотенцесушитель, делая его более функциональным. Полотенцесушитель доступен в версии с водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1275",
      weight: "300",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 106,
      name: "Terma Outcorner 1005/300 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/outcorner/23622750x0.jpg",
              "/assets/outcorner/terma_outcorner_electro_4.jpg",
              "/assets/outcorner/outcorner_1005_300_ral_9016_sx.png",
              "/assets/outcorner/outcorner_1005x300.png",
            ],
            cost: 348.53,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/outcorner/outcorner_0.jpg",
              "/assets/outcorner/outcorner_1005_300_ral_1033_sx.png",
              "/assets/outcorner/terma_outcorner2.jpg",
              "/assets/outcorner/outcorner_1005_300_ral_3002_sx.png",
              "/assets/outcorner/ranksluosciu-dziovintuvas-outcorner_2.jpg",
              "/assets/outcorner/terma_outcorner_electro_3.jpg",
              "/assets/outcorner/884a6eb78de2f5916fb78b9150881f8c.jpg",
              "/assets/outcorner/outcorner_1005x300.png",
            ],
            cost: 365.87,
          },
        },
      ],
      desc: `Там, где ведется поиски свободного пространства и использовать каждый его сантиметр, там используются нестандартные решения. Декоративный полотенцесушитель Outcorner идеально подходит для обустройства небольших, искусно оформленных помещений. Он характеризуется оригинальной эстетикой и интересным и функциональным расположением профилей. Outcorner идеально подходит для помещений, в которых есть колонны и выступающие плоскости где Outcorner может быть интересным и продуманным решением планировки. Дополнительные крючки ZIP дополняют полотенцесушитель, делая его более функциональным. Полотенцесушитель доступен в версии с водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "1005",
      weight: "300",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 107,
      name: "Terma Outcorner 735/300 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/outcorner/1077815_54585454.jpg",
              "/assets/outcorner/outcorner_735_300_ral_9016_sx.png",
              "/assets/outcorner/outcorner_735_355_3_1.jpg",
              "/assets/outcorner/outcorner_735x300.png",
            ],
            cost: 317.32,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/outcorner/outcorner_735_300_ral_3018_sx.png",
              "/assets/outcorner/terma_outcorner_electro_3.jpg",
              "/assets/outcorner/terma_outcorner2.jpg",
              "/assets/outcorner/ranksluosciu-dziovintuvas-outcorner_2.jpg",
              "/assets/outcorner/outcorner_735_300_ral_8002_sx.png",
              "/assets/outcorner/22626_2_1024.jpg",
              "/assets/outcorner/terma_outcorner1.png",
              "/assets/outcorner/outcorner_735x300.png",
            ],
            cost: 332.93,
          },
        },
      ],
      desc: `Там, где ведется поиски свободного пространства и использовать каждый его сантиметр, там используются нестандартные решения. Декоративный полотенцесушитель Outcorner идеально подходит для обустройства небольших, искусно оформленных помещений. Он характеризуется оригинальной эстетикой и интересным и функциональным расположением профилей. Outcorner идеально подходит для помещений, в которых есть колонны и выступающие плоскости где Outcorner может быть интересным и продуманным решением планировки. Дополнительные крючки ZIP дополняют полотенцесушитель, делая его более функциональным. Полотенцесушитель доступен в версии с водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "735",
      weight: "300",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
    {
      id: 108,
      name: "Terma Outcorner 465/350 полотенцесушитель",
      color: [
        {
          Белый: {
            imgs: [
              "/assets/outcorner/outcorner_465_300.jpg",
              "/assets/outcorner/outcorner_465_300_ral_9016_sx.png",
              "/assets/outcorner/outcorner_465x300.png",
            ],
            cost: 287.84,
          },
        },
        {
          RAL: {
            imgs: [
              "/assets/outcorner/terma_outcorner2.jpg",
              "/assets/outcorner/outcorner_465_300_ral_3001_sx.png",
              "/assets/outcorner/terma_outcorner1.png",
              "/assets/outcorner/outcorner_465_300_ral_2001_sx.png",
              "/assets/outcorner/outcorner_465x300.png",
            ],
            cost: 301.72,
          },
        },
      ],
      desc: `Там, где ведется поиски свободного пространства и использовать каждый его сантиметр, там используются нестандартные решения. Декоративный полотенцесушитель Outcorner идеально подходит для обустройства небольших, искусно оформленных помещений. Он характеризуется оригинальной эстетикой и интересным и функциональным расположением профилей. Outcorner идеально подходит для помещений, в которых есть колонны и выступающие плоскости где Outcorner может быть интересным и продуманным решением планировки. Дополнительные крючки ZIP дополняют полотенцесушитель, делая его более функциональным. Полотенцесушитель доступен в версии с водной, водно-электрической и электрической.`,
      count: "",
      producer: "TERMA Польша",
      typeConnect: "электрический / закрытый контур / комбинированный",
      height: "735",
      weight: "300",
      glub: "90",
      tenToComplect: "отдельно",
      ConnectTo: ["справа", "слева", "скрытое", "в розетку"],
      complect: "настенные крепления",
      tenWatt: "300",
      guaranty: "8",
      recommendations: [],
    },
  ],
};
